name: Ruby
on: [push]
jobs:
  build:
    name: Run Build
    runs-on: centos-latest
    steps:
    - name: Actions Checkout
      uses: actions/checkout@master

    - name: Actions Setup Ruby 2.6.x
      uses: actions/setup-ruby@master
      with:
        version: 2.6.x

    - name: Setup Source
      run: |
        gem update --system
        gem install bundler
        bundle install
        bundle update
        rake list:companies_id_ruby
        bundle exec jekyll build
